version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "4024MB"
    image: tensorrt
    #build:
    #  context: .
    #  dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
    ## Uncomment this block for nvidia gpu support
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    count: 1
                    capabilities: [gpu]
    environment:
      YOLO_MODELS: ""

    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8080:8080"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
